#!/bin/sh
#
# @name 3DR Iris Quadrotor SITL (Vision)
#
# @type Quadrotor Wide
#

. ${R}etc/init.d-posix/airframes/10016_iris

# EKF2: Vision position and heading
param set-default EKF2_AID_MASK 24
param set-default EKF2_EV_DELAY 200

param set-default EKF2_HGT_MODE 3
param set-default EKF2_MAG_TYPE 5
param set-default EKF2_ASP_DELAY 50
param set-default EKF2_OF_DELAY 0
param set-default EKF2_MIN_OBS_DT 20
param set-default EKF2_EV_POS_X 0
param set-default EKF2_EV_POS_Y 0
param set-default EKF2_EV_POS_Z 0
param set-default EKF2_EVP_NOISE 0.1
param set-default EKF2_EVA_NOISE 0.05

# LPE: Vision + baro
param set-default LPE_FUSION 132

# AEQ: External heading set to use vision input
param set-default ATT_EXT_HDG_M 1
