#!/bin/sh
#
# @name Gazebo x500 depth
#
# @type Quadrotor
#

PX4_SIM_MODEL=${PX4_SIM_MODEL:=x500_depth}

. ${R}etc/init.d-posix/airframes/4001_gz_x500

param set-default EKF2_MAG_TYPE 5
param set-default EKF2_EV_DELAY 200
param set-default EKF2_HGT_REF 3
param set-default EKF2_EV_CTRL 11
param set-default EKF2_GPS_CTRL 0

# Disable required QGroundControl link
param set-default NAV_DLL_ACT 0
